apiVersion: v1
kind: ServiceAccount
metadata:
  name: appdynamics-infraviz
  namespace: appdynamics
---
apiVersion: cluster.appdynamics.com/v1alpha1
kind: InfraViz
metadata:
  name: appdynamics-infraviz
  namespace: appdynamics
spec:
  controllerUrl: "https://aksorn-pov.saas.appdynamics.com:443"
  image: "docker.io/appdynamics/machine-agent:latest"
  account: "aksorn-pov"
  enableContainerHostId: true
